"""Centralised backend user-facing strings (API error messages, report labels).

All strings that may reach a human live here, keyed by locale, so a Portuguese UI/report
can be produced without touching call sites. Front-end strings live in ``frontend/js/i18n.js``.
"""

# ruff: noqa: E501  (string table: long user-facing sentences stay on one line)
from __future__ import annotations

import contextlib
from typing import Final

SUPPORTED_LOCALES: Final = ("en", "pt")

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "health.ok": "ok",
        "health.degraded": "degraded",
        "neo4j.connected": "connected",
        "neo4j.unavailable": "unavailable",
        "error.neo4j_unavailable": "Neo4j is unavailable. Start the database and retry.",
        "error.generic": "Request failed.",
        "error.not_found": "Not found.",
        "error.conflict": "This relationship already exists.",
        "error.validation": "Invalid data.",
        "error.invalid_edge": "{source_label} → {target_label} cannot use {rel}.",
        "error.invalid_edge.allowed": "Allowed here: {allowed}.",
        "error.invalid_edge.reverse": "The opposite direction allows: {reverse_allowed}.",
        "error.invalid_edge.none": "No relationship type connects these two labels.",
        "error.passive_guard": (
            "Collector '{collector}' would interact with the target and PASSIVE_ONLY is on. "
            "Refused."
        ),
        "error.collector_input": "This collector cannot run with that input.",
        "error.collector_upstream": (
            "Collector '{collector}' got no usable answer from its source: {reason}. "
            "Check your connection or retry later; the source may be slow."
        ),
        # --- analysis / report ---
        "report.title": "Passive attack-surface report",
        "report.subtitle": "Generated by {app} on {date}",
        "report.project": "Project",
        "report.target": "Target organization",
        "report.seed": "Seed domain",
        "report.summary": "Summary",
        "report.verdict_pass": "All three validation criteria are met.",
        "report.verdict_fail": "{n} of 3 validation criteria are met.",
        "report.criteria": "Validation criteria",
        "report.criterion": "Criterion",
        "report.result": "Result",
        "report.value": "Value",
        "report.threshold": "Threshold",
        "report.evidence": "Evidence",
        "report.pass": "PASS",
        "report.fail": "FAIL",
        "report.c1": "Coverage of at least three of the four axes",
        "report.c2": "At least one path from the public seed to an OT asset",
        "report.c3": "At least one cross-axis relationship classified CRITICO or ALTO",
        "report.axis_evidence": "{axis}: {n} node(s)",
        "report.path_evidence": "{hops} hop(s) to “{target}”",
        "report.path_reason.no_seed": "No seed: the project has neither an Organizacao anchor nor a seed domain node.",
        "report.path_reason.no_ot": "No OT asset (layer TO) in the project.",
        "report.path_reason.unreachable": "No directed path from the seed reaches an OT asset.",
        "report.path_reason.gds_unavailable": "GDS plugin not installed; weighted path skipped.",
        "report.manual": "analyst override",
        "report.path": "Seed-to-OT path",
        "report.path_hops": "Shortest path (hops)",
        "report.path_weighted": "Cheapest path (attacker effort, GDS Dijkstra)",
        "report.hops": "hops",
        "report.cost": "total effort",
        "report.entry_policy": "Entry points",
        "report.entry.digital": "Dominio nodes anchored to the organization (public seed)",
        "report.entry.any": "any node anchored to the organization",
        "report.step": "Step",
        "report.from": "From",
        "report.relationship": "Relationship",
        "report.to": "To",
        "report.weight": "Effort",
        "report.high_impact": "High-impact cross-axis relationships",
        "report.high_impact_note": "Ranked by risk level (Tabela 2), then impact (Tabela 8). * = analyst override.",
        "report.classified": "All classified relationships",
        "report.unclassified": "Cross-axis relationships without a Tabela 8 rule",
        "report.unclassified_note": "These crossings are not covered by a thesis rule; set the impact manually in the edge editor if warranted.",
        "report.rule": "Rule",
        "report.impact": "Impact",
        "report.probability": "Probability",
        "report.risk": "Risk",
        "report.cross_axis": "Cross-axis",
        "report.yes": "yes",
        "report.no": "no",
        "report.none": "none",
        "report.evidence_key.cve_high": "known CVE with CVSS ≥ 7",
        "report.evidence_key.cve_known": "known CVE",
        "report.evidence_key.remote_auth": "exposed remote-authentication service",
        "report.evidence_key.non_production": "non-production environment",
        "report.evidence_key.leaked_credential": "documented credential leak",
        "report.evidence_key.supplier_access": "third-party access to infrastructure",
        "report.evidence_key.direct_ot_access": "direct access to an industrial device",
        "report.centrality": "Central nodes",
        "report.centrality_note_gds": "Betweenness and degree centrality (GDS, undirected projection).",
        "report.centrality_note_cypher": "Degree centrality (GDS not installed).",
        "report.node": "Node",
        "report.type": "Type",
        "report.axis": "Axis",
        "report.degree": "Degree",
        "report.betweenness": "Betweenness",
        "report.inventory": "Inventory",
        "report.nodes": "Nodes",
        "report.edges": "Relationships",
        "report.by_label": "Nodes by type",
        "report.by_axis": "Nodes by axis",
        "report.by_rel": "Relationships by type",
        "report.count": "Count",
        "report.node_inventory": "Node inventory",
        "report.source": "Source",
        "report.reviewed": "Reviewed",
        "report.method": "Method notes",
        "report.method_text": "Impact follows thesis Tabela 8; probability is a heuristic (overridable per relationship); the risk level follows Tabela 2, with CRITICO impact read in the ALTO column. Paths follow relationship direction from the seed; the anchoring relationship (PERTENCE_A, FORNECE_PARA, TRABALHA_EM) is traversed in reverse. Collection was passive-only: no built-in collector contacts the target.",
        "report.extension_mark": "extension",
    },
    "pt": {
        "health.ok": "ok",
        "health.degraded": "degradado",
        "neo4j.connected": "conectado",
        "neo4j.unavailable": "indisponível",
        "error.neo4j_unavailable": "Neo4j indisponível. Inicie o banco de dados e tente novamente.",
        "error.generic": "A requisição falhou.",
        "error.not_found": "Não encontrado.",
        "error.conflict": "Essa relação já existe.",
        "error.validation": "Dados inválidos.",
        "error.invalid_edge": "{source_label} → {target_label} não pode usar {rel}.",
        "error.invalid_edge.allowed": "Permitido aqui: {allowed}.",
        "error.invalid_edge.reverse": "A direção oposta permite: {reverse_allowed}.",
        "error.invalid_edge.none": "Nenhum tipo de relação conecta esses dois rótulos.",
        "error.passive_guard": (
            "O coletor '{collector}' interagiria com o alvo e PASSIVE_ONLY está ativo. Recusado."
        ),
        "error.collector_input": "Este coletor não pode rodar com essa entrada.",
        "error.collector_upstream": (
            "O coletor '{collector}' não obteve resposta útil da fonte: {reason}. "
            "Verifique a conexão ou tente mais tarde; a fonte pode estar lenta."
        ),
        # --- análise / relatório ---
        "report.title": "Relatório de superfície de ataque passiva",
        "report.subtitle": "Gerado por {app} em {date}",
        "report.project": "Projeto",
        "report.target": "Organização-alvo",
        "report.seed": "Domínio semente",
        "report.summary": "Resumo",
        "report.verdict_pass": "Os três critérios de validação foram atendidos.",
        "report.verdict_fail": "{n} de 3 critérios de validação foram atendidos.",
        "report.criteria": "Critérios de validação",
        "report.criterion": "Critério",
        "report.result": "Resultado",
        "report.value": "Valor",
        "report.threshold": "Limiar",
        "report.evidence": "Evidência",
        "report.pass": "ATENDIDO",
        "report.fail": "NÃO ATENDIDO",
        "report.c1": "Cobertura de pelo menos três dos quatro eixos",
        "report.c2": "Pelo menos um caminho da semente pública até um ativo de TO",
        "report.c3": "Pelo menos uma relação entre eixos classificada como CRÍTICO ou ALTO",
        "report.axis_evidence": "{axis}: {n} nó(s)",
        "report.path_evidence": "{hops} salto(s) até “{target}”",
        "report.path_reason.no_seed": "Sem semente: o projeto não tem nó âncora Organizacao nem nó de domínio semente.",
        "report.path_reason.no_ot": "Nenhum ativo de TO (camada TO) no projeto.",
        "report.path_reason.unreachable": "Nenhum caminho direcionado a partir da semente alcança um ativo de TO.",
        "report.path_reason.gds_unavailable": "Plugin GDS não instalado; caminho ponderado ignorado.",
        "report.manual": "definido pelo analista",
        "report.path": "Caminho semente → TO",
        "report.path_hops": "Caminho mais curto (saltos)",
        "report.path_weighted": "Caminho de menor esforço (Dijkstra, GDS)",
        "report.hops": "saltos",
        "report.cost": "esforço total",
        "report.entry_policy": "Pontos de entrada",
        "report.entry.digital": "nós Dominio ancorados à organização (semente pública)",
        "report.entry.any": "qualquer nó ancorado à organização",
        "report.step": "Passo",
        "report.from": "De",
        "report.relationship": "Relação",
        "report.to": "Para",
        "report.weight": "Esforço",
        "report.high_impact": "Relações entre eixos de alto impacto",
        "report.high_impact_note": "Ordenadas por nível de risco (Tabela 2) e impacto (Tabela 8). * = definido pelo analista.",
        "report.classified": "Todas as relações classificadas",
        "report.unclassified": "Relações entre eixos sem regra na Tabela 8",
        "report.unclassified_note": "Esses cruzamentos não são cobertos por uma regra da monografia; defina o impacto manualmente no editor de relação, se cabível.",
        "report.rule": "Regra",
        "report.impact": "Impacto",
        "report.probability": "Probabilidade",
        "report.risk": "Risco",
        "report.cross_axis": "Entre eixos",
        "report.yes": "sim",
        "report.no": "não",
        "report.none": "nenhum",
        "report.evidence_key.cve_high": "CVE conhecida com CVSS ≥ 7",
        "report.evidence_key.cve_known": "CVE conhecida",
        "report.evidence_key.remote_auth": "serviço de autenticação remota exposto",
        "report.evidence_key.non_production": "ambiente não produtivo",
        "report.evidence_key.leaked_credential": "vazamento de credencial documentado",
        "report.evidence_key.supplier_access": "acesso de terceiro à infraestrutura",
        "report.evidence_key.direct_ot_access": "acesso direto a dispositivo industrial",
        "report.centrality": "Nós centrais",
        "report.centrality_note_gds": "Centralidade de intermediação e grau (GDS, projeção não direcionada).",
        "report.centrality_note_cypher": "Centralidade de grau (GDS não instalado).",
        "report.node": "Nó",
        "report.type": "Tipo",
        "report.axis": "Eixo",
        "report.degree": "Grau",
        "report.betweenness": "Intermediação",
        "report.inventory": "Inventário",
        "report.nodes": "Nós",
        "report.edges": "Relações",
        "report.by_label": "Nós por tipo",
        "report.by_axis": "Nós por eixo",
        "report.by_rel": "Relações por tipo",
        "report.count": "Quantidade",
        "report.node_inventory": "Inventário de nós",
        "report.source": "Fonte",
        "report.reviewed": "Revisado",
        "report.method": "Notas de método",
        "report.method_text": "O impacto segue a Tabela 8 da monografia; a probabilidade é heurística (sobrescrevível por relação); o nível de risco segue a Tabela 2, com impacto CRÍTICO lido na coluna ALTO. Os caminhos seguem a direção das relações a partir da semente; a relação de ancoragem (PERTENCE_A, FORNECE_PARA, TRABALHA_EM) é percorrida no sentido inverso. A coleta foi exclusivamente passiva: nenhum coletor embutido contata o alvo.",
        "report.extension_mark": "extensão",
    },
}


def t(key: str, locale: str = "en", **vars: object) -> str:
    """Translate ``key`` for ``locale`` (fallback: English, then the key), filling ``{vars}``.

    ``allowed``/``reverse_allowed`` lists are joined so the message reads naturally; for
    ``error.invalid_edge`` the hint sentence is appended."""
    table = _STRINGS.get(locale) or _STRINGS["en"]
    text = table.get(key) or _STRINGS["en"].get(key, key)
    fmt = {k: ", ".join(v) if isinstance(v, list | tuple) else v for k, v in vars.items()}
    with contextlib.suppress(KeyError, IndexError):
        text = text.format(**fmt)
    if key == "error.invalid_edge" and "source_label" in vars:
        if vars.get("allowed"):
            text += " " + t("error.invalid_edge.allowed", locale, **vars)
        elif vars.get("reverse_allowed"):
            text += " " + t("error.invalid_edge.reverse", locale, **vars)
        else:
            text += " " + t("error.invalid_edge.none", locale)
    return text
