#!/usr/bin/env bash
# Copy pinned front-end libraries into frontend/vendor so the app never needs a CDN.
# Requires npm (only at vendoring time; the vendored files are committed).
set -euo pipefail
cd "$(dirname "$0")/.."

VIS_NETWORK_VERSION="${VIS_NETWORK_VERSION:-10.1.2}"
MARKED_VERSION="${MARKED_VERSION:-18.0.13}"
PLEX_VERSION="${PLEX_VERSION:-5.3.0}"
JBMONO_VERSION="${JBMONO_VERSION:-5.3.0}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
VENDOR=frontend/vendor
mkdir -p "$VENDOR/fonts"

echo "==> fetching packages with npm"
( cd "$WORK" && npm init -y >/dev/null && npm install --silent --no-audit --no-fund \
    "vis-network@${VIS_NETWORK_VERSION}" \
    "marked@${MARKED_VERSION}" \
    "@fontsource/ibm-plex-sans@${PLEX_VERSION}" \
    "@fontsource/jetbrains-mono@${JBMONO_VERSION}" )

NM="$WORK/node_modules"
cp "$NM/vis-network/standalone/umd/vis-network.min.js" "$VENDOR/vis-network.min.js"
cp "$NM/vis-network/LICENSE-MIT" "$VENDOR/vis-network.LICENSE"
cp "$NM/marked/lib/marked.umd.js" "$VENDOR/marked.umd.js"
cp "$NM/marked/LICENSE" "$VENDOR/marked.LICENSE"

# Latin subsets only, regular + semibold; woff2 is supported by WebKitGTK and every browser.
for w in 400 600; do
  cp "$NM/@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-${w}-normal.woff2" "$VENDOR/fonts/"
  cp "$NM/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-${w}-normal.woff2" "$VENDOR/fonts/"
done
cp "$NM/@fontsource/ibm-plex-sans/LICENSE" "$VENDOR/fonts/ibm-plex-sans.LICENSE"
cp "$NM/@fontsource/jetbrains-mono/LICENSE" "$VENDOR/fonts/jetbrains-mono.LICENSE"

cat > "$VENDOR/fonts.css" <<CSS
/* Generated by scripts/vendor-frontend.sh — local fonts, no network access. */
@font-face { font-family: "IBM Plex Sans"; font-style: normal; font-weight: 400; font-display: swap;
  src: url("fonts/ibm-plex-sans-latin-400-normal.woff2") format("woff2"); }
@font-face { font-family: "IBM Plex Sans"; font-style: normal; font-weight: 600; font-display: swap;
  src: url("fonts/ibm-plex-sans-latin-600-normal.woff2") format("woff2"); }
@font-face { font-family: "JetBrains Mono"; font-style: normal; font-weight: 400; font-display: swap;
  src: url("fonts/jetbrains-mono-latin-400-normal.woff2") format("woff2"); }
@font-face { font-family: "JetBrains Mono"; font-style: normal; font-weight: 600; font-display: swap;
  src: url("fonts/jetbrains-mono-latin-600-normal.woff2") format("woff2"); }
CSS

cat > "$VENDOR/VERSIONS" <<TXT
vis-network ${VIS_NETWORK_VERSION}
marked ${MARKED_VERSION}
@fontsource/ibm-plex-sans ${PLEX_VERSION}
@fontsource/jetbrains-mono ${JBMONO_VERSION}
TXT

echo "==> vendored into $VENDOR:"
ls -la "$VENDOR" "$VENDOR/fonts" | grep -vE "^total|^d"
